export const editionData = {
  logo: "/astro/logo-icon.png",
  title: "ASTRO SDQ - 5TA EDICIÓN",
  paragraph1: "CADA ARTISTA LLEVA CONSIGO UNA HISTORIA, UNA TÉCNICA Y UNA FORMA DE ENTENDER EL ARTE. DESDE REPÚBLICA DOMINICANA, ASTRO SDQ REÚNE ESAS MIRADAS EN UN ENTORNO DONDE EL INTERCAMBIO Y EL CRECIMIENTO TOMAN PROTAGONISMO.",
  paragraph2: "MÁS QUE UN EVENTO,\nES UNA EXPERIENCIA QUE HONRA\nEL CAMINO DE CADA TATUADOR.",
  location: "SANTO DOMINGO\n2027",
  coordinates: "18°28'55.5 N 69°54'41.9 W",
};